### ISSUE TITLE
Full Layer Testing on z/OS

### ISSUE THREAD

**Issue by Deegrin** [dwadler/QGIS#4]
We've just been testing with DB2 for LUW so far. Set up a DB2 for z/OS test environment and verify that loading a full layer works the same. Consider documenting the test environment setup procedure in one place.

There is currently a problem with the WKB data being returned from z/OS versus LUW.

**Comment by dwadler** [comment]
I opened a high-priority defect against the QGIS code. https://hub.qgis.org/issues/14204
I was able diagnose and fix the problem but would rather have the QGIS team fix it.

If I include / commit this in db2-development, is it possible to remove it later before the merge into QGIS master?

**Comment by Deegrin** [comment]
@dwadler, thanks for looking into and handling all this. I've been following the QGIS mailing list and read your bug report.

> If I include / commit this in db2-development, is it possible to remove it later before the merge into QGIS master?

Git does support removing a specific commit or adjacent commits, but I don't think it specializes in it. I could probably do the research and try it when the time comes - sounds fun. If anything, we could probably just bookmark the relevant commits and manually undo the changes, haha.

**Comment by dwadler** [comment]
My concern is that I modified some of the QGIS core classes to get WKB to work.  Even if I copy over the QGIS master fixed versions, it will probably still look like a change.

I think I won't worry about it and will push my changes up to our db2-development repository.
I'm trying to sync with the QGIS master and it seems like it would like me to do this.

**Comment by Deegrin** [comment]
If you're only concerned about the QGIS core classes, Git makes it easy to overwrite files from other branches. So when the time comes, we can just overwrite the relevant QGIS core classes in db2-development with the latest files from the master branch. A pull request diff shouldn't show anything was changed, either.

**Comment by dwadler** [comment]
The QGIS master has committed the fixes to WKB support for "other-endian".

I synced our master with the QGIS master and built everything - it seems to work with both z/OS and LUW without the patches I had put in.

There is a new QgsDb2GeometryColumn class and source files. This consolidates access to ST_Geometry_Columns to one place and provides a convenience method to populate a QgsDb2LayerProperty structure.

Closing this issue.
Since this changes CMakeList.txt, you will probably need to re-run cmake-gui and re-build.
